# Generated by Django 4.1.4 on 2023-01-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecord',
            old_name='topic_name',
            new_name='name',
        ),
    ]
